### ISSUE TITLE
Peer-to-Peer  Code Review: Morning Session

### ISSUE THREAD

**Issue by Markotweyo** [HtetNaing0814/rex-shuhad-tracey-portfolio#1]
- I suggest you put more styles in the external styles files instead of inline styles

**Comment by MxoDevops** [comment]
I suggest that you wrap the nav element inside the header for more semantic accuracy.

**Comment by Owusu-Desmond** [comment]
In the project, I notice 

- [ ] You have `.vscode` folder present in the project but this is not needed.
- [ ] You should Update your ReadMe file and make it descriptive using readMe file template.
- [ ] You should use html semantic tags to wrap your container after the `nav`.

**Comment by rex-9** [comment]
Ok guys thank you so much for your reviews.
